export const SOCKET_EVENTS = {
  COMMON: {
    ONLINE: "socket.common.online",
    OFFLINE: "socket.common.offline",
    TYPING: "socket.common.typing",
    STOP_TYPING: "socket.common.stop-typing",
    DETAILS: "socket.common.connection-details",
    JOIN: "socket.common.join",
    LEAVE: "socket.common.leave",

    ONLINE_CLIENT: "socket.common.online.client",
    OFFLINE_CLIENT: "socket.common.offline.client",
    TYPING_CLIENT: "socket.common.typing.client",
    STOP_TYPING_CLIENT: "socket.common.stop-typing.client",
    DETAILS_CLIENT: "socket.common.connection-details.client",
    JOIN_CLIENT: "socket.common.join.client",
    LEAVE_CLIENT: "socket.common.leave.client",
  },
  GROUP: {
    ADD: "socket.group.add",
    REMOVE: "socket.group.remove",
    LEAVE: "socket.group.leave",
    UPDATE: "socket.group.update",
    MAKE_ADMIN: "socket.group.make-admin",
    REMOVE_ADMIN: "socket.group.remove-admin",

    ADD_CLIENT: "socket.group.add.client",
    REMOVE_CLIENT: "socket.group.remove.client",
    LEAVE_CLIENT: "socket.group.leave.client",
    UPDATE_CLIENT: "socket.group.update.client",
    MAKE_ADMIN_CLIENT: "socket.group.make-admin.client",
    REMOVE_ADMIN_CLIENT: "socket.group.remove-admin.client",
  },
  MESSAGE: {
    ADD: "socket.message.add",
    UPDATE: "socket.message.update",
    DELETE: "socket.message.delete",
    STAR: "socket.message.star",
    PIN: "socket.message.pin",
    REACTION: "socket.message.reaction",
    SEEN: "socket.message.seen",
    RECEIVED: "socket.message.received",

    ADD_CLIENT: "socket.message.add.client",
    UPDATE_CLIENT: "socket.message.update.client",
    DELETE_CLIENT: "socket.message.delete.client",
    STAR_CLIENT: "socket.message.star.client",
    PIN_CLIENT: "socket.message.pin.client",
    REACTION_CLIENT: "socket.message.reaction.client",
    SEEN_CLIENT: "socket.message.seen.client",
    RECEIVED_CLIENT: "socket.message.received.client",
  },
} as const;
